### PR TITLE
Add tests for isSame, isBefore, isAfter

### PR DESCRIPTION
**Pull request by BePo65**
Add more tests for the compare functions isSame, isBefore, isAfter.

### CODE REVIEW

**Review by g-mero — CHANGES_REQUESTED** [review]
I think the first parameter(that) should not be optional

**Comment by BePo65** [comment]
Basically you are right (as what would be the use of `esday.isSame()`.

But in the documentation for 'moment' (the reference for dayjs and therefore even for esday) there is a section about that topic (see the [moment docs](https://momentjs.com/docs/#/query/is-same/):

> NOTE: moment().isSame() has undefined behavior and should not be used!

For me this means: we could use `.isSame()`, but we should not. So I added the possibility to use it (at the risk of the programmer doing this).

**Comment by g-mero** [comment]
Since this is a TypeScript project, I believe the first parameter of isSame should be non-optional. If we make it optional, programmers might think it’s valid to omit the parameter without understanding the behavior (which, in our current code, defaults to comparing with today’s date). This could lead to confusion and unclear usage.

This doesn’t conflict with what you mentioned—programmers can still use .isSame() without ts-check, but TypeScript ensures clarity and prevents unintended usage when type checking is enabled.

**Comment by g-mero** [comment]
@BePo65  Have you reviewed the README I just updated? I’m considering moving the locale system into plugins to make the core simpler. What’s your opinion?

**Review by g-mero — APPROVED** [review]

**Pull request merged**
